// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.GoogleSignInUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class GoogleSignInUIMap
    {
        
        #region Properties
        public UIPersonifyGoogleSignInMainWindow UIPersonifyGoogleSignInMainWindow
        {
            get
            {
                if ((this.mUIPersonifyGoogleSignInMainWindow == null))
                {
                    this.mUIPersonifyGoogleSignInMainWindow = new UIPersonifyGoogleSignInMainWindow();
                }
                return this.mUIPersonifyGoogleSignInMainWindow;
            }
        }
        
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient();
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyGoogleSignInMainWindow mUIPersonifyGoogleSignInMainWindow;
        
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyGoogleSignInMainWindow : WpfWindow
    {
        
        public UIPersonifyGoogleSignInMainWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfImage UIPersonifyLogoImage
        {
            get
            {
                if ((this.mUIPersonifyLogoImage == null))
                {
                    this.mUIPersonifyLogoImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIPersonifyLogoImage.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPersonifyLogoImage;
            }
        }
        
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIPersonifyLogoImage;
        
        private WpfButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient()
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            #endregion
        }
        
        #region Properties
        public UISigninGoogleAccountsDocument UISigninGoogleAccountsDocument
        {
            get
            {
                if ((this.mUISigninGoogleAccountsDocument == null))
                {
                    this.mUISigninGoogleAccountsDocument = new UISigninGoogleAccountsDocument(this);
                }
                return this.mUISigninGoogleAccountsDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISigninGoogleAccountsDocument mUISigninGoogleAccountsDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISigninGoogleAccountsDocument : HtmlDocument
    {
        
        public UISigninGoogleAccountsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in - Google Accounts";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/AccountChooser";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fscope%3Dhttps%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds%2F%2Bemail%2Bprofile%26response_type%3Dcode%26access_type%3Doffline%26redirect_uri%3Durn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob%26approval_prompt%3Dauto%26client_id%3D896229751225-n6ip3caqv2f02hibt1u8rtu6f6ne2rtv.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3D-42879badaa09555&btmpl=authsub&hl=en";
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIChooseanaccountPane
        {
            get
            {
                if ((this.mUIChooseanaccountPane == null))
                {
                    this.mUIChooseanaccountPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIChooseanaccountPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIChooseanaccountPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIChooseanaccountPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Choose an account ";
                    this.mUIChooseanaccountPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIChooseanaccountPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "banner";
                    this.mUIChooseanaccountPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=banner";
                    this.mUIChooseanaccountPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    #endregion
                }
                return this.mUIChooseanaccountPane;
            }
        }
        
        public HtmlImage UIGoogleImage
        {
            get
            {
                if ((this.mUIGoogleImage == null))
                {
                    this.mUIGoogleImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIGoogleImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIGoogleImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIGoogleImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Google";
                    this.mUIGoogleImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/accounts/ui/logo_2x.png";
                    this.mUIGoogleImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://ssl.gstatic.com/accounts/ui/logo_2x.png";
                    this.mUIGoogleImage.FilterProperties[HtmlImage.PropertyNames.Class] = "logo";
                    this.mUIGoogleImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "class=logo alt=Google src=\"//ssl.gstatic";
                    this.mUIGoogleImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIGoogleImage;
            }
        }
        
        public HtmlHyperlink UIAddaccountHyperlink
        {
            get
            {
                if ((this.mUIAddaccountHyperlink == null))
                {
                    this.mUIAddaccountHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAddaccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "account-chooser-add-account";
                    this.mUIAddaccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAddaccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAddaccountHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Add account ";
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/AddSession";
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = @"https://accounts.google.com/AddSession?sacu=1&btmpl=authsub&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fscope%3Dhttps%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds%2F%2Bemail%2Bprofile%26response_type%3Dcode%26access_type%3Doffline%26redirect_uri%3Durn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob%26approval_prompt%3Dauto%26client_id%3D896229751225-n6ip3caqv2f02hibt1u8rtu6f6ne2rtv.apps.googleusercontent.com%26hl%3Den%26from_login%3D1%26as%3D-42879badaa09555&hl=en&service=lso";
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=account-chooser-add-account href=\"htt";
                    this.mUIAddaccountHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIAddaccountHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIChooseanaccountPane;
        
        private HtmlImage mUIGoogleImage;
        
        private HtmlHyperlink mUIAddaccountHyperlink;
        #endregion
    }
}
