// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.InstallerUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class InstallerUIMap
    {
        
        #region Properties
        public UIPersonifySetupWindow UIPersonifySetupWindow
        {
            get
            {
                if ((this.mUIPersonifySetupWindow == null))
                {
                    this.mUIPersonifySetupWindow = new UIPersonifySetupWindow();
                }
                return this.mUIPersonifySetupWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifySetupWindow mUIPersonifySetupWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifySetupWindow : WinWindow
    {
        
        public UIPersonifySetupWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Personify Setup ";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UILicenseAgreementWindow UILicenseAgreementWindow
        {
            get
            {
                if ((this.mUILicenseAgreementWindow == null))
                {
                    this.mUILicenseAgreementWindow = new UILicenseAgreementWindow(this);
                }
                return this.mUILicenseAgreementWindow;
            }
        }
        
        public UIPleasereviewthelicenWindow UIPleasereviewthelicenWindow
        {
            get
            {
                if ((this.mUIPleasereviewthelicenWindow == null))
                {
                    this.mUIPleasereviewthelicenWindow = new UIPleasereviewthelicenWindow(this);
                }
                return this.mUIPleasereviewthelicenWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIPersonifySetupTitleBar UIPersonifySetupTitleBar
        {
            get
            {
                if ((this.mUIPersonifySetupTitleBar == null))
                {
                    this.mUIPersonifySetupTitleBar = new UIPersonifySetupTitleBar(this);
                }
                return this.mUIPersonifySetupTitleBar;
            }
        }
        
        public UIIAgreeWindow UIIAgreeWindow
        {
            get
            {
                if ((this.mUIIAgreeWindow == null))
                {
                    this.mUIIAgreeWindow = new UIIAgreeWindow(this);
                }
                return this.mUIIAgreeWindow;
            }
        }
        
        public UICancelWindow UICancelWindow
        {
            get
            {
                if ((this.mUICancelWindow == null))
                {
                    this.mUICancelWindow = new UICancelWindow(this);
                }
                return this.mUICancelWindow;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIShowdetailsWindow UIShowdetailsWindow
        {
            get
            {
                if ((this.mUIShowdetailsWindow == null))
                {
                    this.mUIShowdetailsWindow = new UIShowdetailsWindow(this);
                }
                return this.mUIShowdetailsWindow;
            }
        }
        
        public UIBackWindow UIBackWindow
        {
            get
            {
                if ((this.mUIBackWindow == null))
                {
                    this.mUIBackWindow = new UIBackWindow(this);
                }
                return this.mUIBackWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UILicenseAgreementWindow mUILicenseAgreementWindow;
        
        private UIPleasereviewthelicenWindow mUIPleasereviewthelicenWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIPersonifySetupTitleBar mUIPersonifySetupTitleBar;
        
        private UIIAgreeWindow mUIIAgreeWindow;
        
        private UICancelWindow mUICancelWindow;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIShowdetailsWindow mUIShowdetailsWindow;
        
        private UIBackWindow mUIBackWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1046";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinControl UIPersonifyLogo
        {
            get
            {
                if ((this.mUIPersonifyLogo == null))
                {
                    this.mUIPersonifyLogo = new WinControl(this);
                    #region Search Criteria
                    this.mUIPersonifyLogo.SearchProperties[UITestControl.PropertyNames.Name] = "Please review the license terms before installing Personify.";
                    this.mUIPersonifyLogo.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUIPersonifyLogo.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIPersonifyLogo;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIPersonifyLogo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILicenseAgreementWindow : WinWindow
    {
        
        public UILicenseAgreementWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1037";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinText UILicenseAgreementText
        {
            get
            {
                if ((this.mUILicenseAgreementText == null))
                {
                    this.mUILicenseAgreementText = new WinText(this);
                    #region Search Criteria
                    this.mUILicenseAgreementText.SearchProperties[WinText.PropertyNames.Name] = "License Agreement";
                    this.mUILicenseAgreementText.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUILicenseAgreementText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUILicenseAgreementText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPleasereviewthelicenWindow : WinWindow
    {
        
        public UIPleasereviewthelicenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1038";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinText UIPleasereviewthelicenText
        {
            get
            {
                if ((this.mUIPleasereviewthelicenText == null))
                {
                    this.mUIPleasereviewthelicenText = new WinText(this);
                    #region Search Criteria
                    this.mUIPleasereviewthelicenText.SearchProperties[WinText.PropertyNames.Name] = "Please review the license terms before installing Personify.";
                    this.mUIPleasereviewthelicenText.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIPleasereviewthelicenText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIPleasereviewthelicenText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1000";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPressPageDowntoseethEdit
        {
            get
            {
                if ((this.mUIPressPageDowntoseethEdit == null))
                {
                    this.mUIPressPageDowntoseethEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPressPageDowntoseethEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Press Page Down to see the rest of the agreement.";
                    this.mUIPressPageDowntoseethEdit.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIPressPageDowntoseethEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPressPageDowntoseethEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifySetupTitleBar : WinTitleBar
    {
        
        public UIPersonifySetupTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinButton UIMinimizeButton
        {
            get
            {
                if ((this.mUIMinimizeButton == null))
                {
                    this.mUIMinimizeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinimizeButton.SearchProperties[WinButton.PropertyNames.Name] = "Minimize";
                    this.mUIMinimizeButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIMinimizeButton;
            }
        }
        
        public WinButton UIMaximizeButton
        {
            get
            {
                if ((this.mUIMaximizeButton == null))
                {
                    this.mUIMaximizeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMaximizeButton.SearchProperties[WinButton.PropertyNames.Name] = "Maximize";
                    this.mUIMaximizeButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIMaximizeButton;
            }
        }
        
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMinimizeButton;
        
        private WinButton mUIMaximizeButton;
        
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIIAgreeWindow : WinWindow
    {
        
        public UIIAgreeWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinButton UIIAgreeButton
        {
            get
            {
                if ((this.mUIIAgreeButton == null))
                {
                    this.mUIIAgreeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIAgreeButton.SearchProperties[WinButton.PropertyNames.Name] = "I Agree";
                    this.mUIIAgreeButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIIAgreeButton;
            }
        }
        
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIAgreeButton;
        
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UICancelWindow : WinWindow
    {
        
        public UICancelWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinButton UICancelButton
        {
            get
            {
                if ((this.mUICancelButton == null))
                {
                    this.mUICancelButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICancelButton.SearchProperties[WinButton.PropertyNames.Name] = "Cancel";
                    this.mUICancelButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUICancelButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICancelButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1004";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinProgressBar UIItemProgressBar
        {
            get
            {
                if ((this.mUIItemProgressBar == null))
                {
                    this.mUIItemProgressBar = new WinProgressBar(this);
                    #region Search Criteria
                    this.mUIItemProgressBar.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIItemProgressBar;
            }
        }
        #endregion
        
        #region Fields
        private WinProgressBar mUIItemProgressBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIShowdetailsWindow : WinWindow
    {
        
        public UIShowdetailsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1027";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinButton UIShowdetailsButton
        {
            get
            {
                if ((this.mUIShowdetailsButton == null))
                {
                    this.mUIShowdetailsButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIShowdetailsButton.SearchProperties[WinButton.PropertyNames.Name] = "Show details";
                    this.mUIShowdetailsButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIShowdetailsButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIShowdetailsButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIBackWindow : WinWindow
    {
        
        public UIBackWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "3";
            this.WindowTitles.Add("Personify Setup ");
            #endregion
        }
        
        #region Properties
        public WinButton UIBackButton
        {
            get
            {
                if ((this.mUIBackButton == null))
                {
                    this.mUIBackButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBackButton.SearchProperties[WinButton.PropertyNames.Name] = "< Back";
                    this.mUIBackButton.WindowTitles.Add("Personify Setup ");
                    #endregion
                }
                return this.mUIBackButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBackButton;
        #endregion
    }
}
