// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.LoginUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class LoginUIMap
    {
        
        #region Properties
        public UIPersonifyMainLoginWindow UIPersonifyMainLoginWindow
        {
            get
            {
                if ((this.mUIPersonifyMainLoginWindow == null))
                {
                    this.mUIPersonifyMainLoginWindow = new UIPersonifyMainLoginWindow();
                }
                return this.mUIPersonifyMainLoginWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyMainLoginWindow mUIPersonifyMainLoginWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyMainLoginWindow : WpfWindow
    {
        
        public UIPersonifyMainLoginWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfImage UIPersonifyLogoImage
        {
            get
            {
                if ((this.mUIPersonifyLogoImage == null))
                {
                    this.mUIPersonifyLogoImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIPersonifyLogoImage.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPersonifyLogoImage;
            }
        }
        
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public WpfButton UIGoogleLoginButton
        {
            get
            {
                if ((this.mUIGoogleLoginButton == null))
                {
                    this.mUIGoogleLoginButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIGoogleLoginButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIGoogleLoginButton;
            }
        }
        
        public UIPersonifyAccountLoginFormCustom UIPersonifyAccountLoginFormCustom
        {
            get
            {
                if ((this.mUIPersonifyAccountLoginFormCustom == null))
                {
                    this.mUIPersonifyAccountLoginFormCustom = new UIPersonifyAccountLoginFormCustom(this);
                }
                return this.mUIPersonifyAccountLoginFormCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIPersonifyLogoImage;
        
        private WpfButton mUICloseButton;
        
        private WpfButton mUIGoogleLoginButton;
        
        private UIPersonifyAccountLoginFormCustom mUIPersonifyAccountLoginFormCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyAccountLoginFormCustom : WpfCustom
    {
        
        public UIPersonifyAccountLoginFormCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.PersonifyLoginUC";
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfText UIUsernameText
        {
            get
            {
                if ((this.mUIUsernameText == null))
                {
                    this.mUIUsernameText = new WpfText(this);
                    #region Search Criteria
                    this.mUIUsernameText.SearchProperties[WpfText.PropertyNames.AutomationId] = "UsernameWatermark";
                    this.mUIUsernameText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIUsernameText;
            }
        }
        
        public WpfEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Username";
                    this.mUIUsernameEdit.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WpfText UIPasswordText
        {
            get
            {
                if ((this.mUIPasswordText == null))
                {
                    this.mUIPasswordText = new WpfText(this);
                    #region Search Criteria
                    this.mUIPasswordText.SearchProperties[WpfText.PropertyNames.AutomationId] = "PasswordWatermark";
                    this.mUIPasswordText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPasswordText;
            }
        }
        
        public WpfEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UISignUpText UISignUpText
        {
            get
            {
                if ((this.mUISignUpText == null))
                {
                    this.mUISignUpText = new UISignUpText(this);
                }
                return this.mUISignUpText;
            }
        }
        
        public WpfButton UISigninButton
        {
            get
            {
                if ((this.mUISigninButton == null))
                {
                    this.mUISigninButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISigninButton.SearchProperties[WpfButton.PropertyNames.Name] = "Sign in";
                    this.mUISigninButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISigninButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIUsernameText;
        
        private WpfEdit mUIUsernameEdit;
        
        private WpfText mUIPasswordText;
        
        private WpfEdit mUIPasswordEdit;
        
        private UISignUpText mUISignUpText;
        
        private WpfButton mUISigninButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISignUpText : WpfText
    {
        
        public UISignUpText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Sign Up";
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfHyperlink UISignUpHyperlink
        {
            get
            {
                if ((this.mUISignUpHyperlink == null))
                {
                    this.mUISignUpHyperlink = new WpfHyperlink(this);
                    #region Search Criteria
                    this.mUISignUpHyperlink.SearchProperties[WpfHyperlink.PropertyNames.Name] = "Sign Up";
                    this.mUISignUpHyperlink.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignUpHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WpfHyperlink mUISignUpHyperlink;
        #endregion
    }
}
