// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.LoginUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class LoginUIMap
    {
        
        #region Properties
        public UIPersonifyMainLoginWindow UIPersonifyMainLoginWindow
        {
            get
            {
                if ((this.mUIPersonifyMainLoginWindow == null))
                {
                    this.mUIPersonifyMainLoginWindow = new UIPersonifyMainLoginWindow();
                }
                return this.mUIPersonifyMainLoginWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyMainLoginWindow mUIPersonifyMainLoginWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyMainLoginWindow : WpfWindow
    {
        
        public UIPersonifyMainLoginWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public WpfButton UIPersonifyLoginMainMenu
        {
            get
            {
                if ((this.mUIPersonifyLoginMainMenu == null))
                {
                    this.mUIPersonifyLoginMainMenu = new WpfButton(this);
                    #region Search Criteria
                    this.mUIPersonifyLoginMainMenu.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPersonifyLoginMainMenu;
            }
        }
        
        public UIPersonifySignInDialog UIPersonifySignInDialog
        {
            get
            {
                if ((this.mUIPersonifySignInDialog == null))
                {
                    this.mUIPersonifySignInDialog = new UIPersonifySignInDialog(this);
                }
                return this.mUIPersonifySignInDialog;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICloseButton;
        
        private WpfButton mUIPersonifyLoginMainMenu;
        
        private UIPersonifySignInDialog mUIPersonifySignInDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifySignInDialog : WpfCustom
    {
        
        public UIPersonifySignInDialog(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.PersonifySignInUC";
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfText UISignInText
        {
            get
            {
                if ((this.mUISignInText == null))
                {
                    this.mUISignInText = new WpfText(this);
                    #region Search Criteria
                    this.mUISignInText.SearchProperties[WpfText.PropertyNames.Name] = "Sign In";
                    this.mUISignInText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignInText;
            }
        }
        
        public WpfButton UIGoogleSignInButton
        {
            get
            {
                if ((this.mUIGoogleSignInButton == null))
                {
                    this.mUIGoogleSignInButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIGoogleSignInButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIGoogleSignInButton;
            }
        }
        
        public WpfText UIORText
        {
            get
            {
                if ((this.mUIORText == null))
                {
                    this.mUIORText = new WpfText(this);
                    #region Search Criteria
                    this.mUIORText.SearchProperties[WpfText.PropertyNames.Name] = "or";
                    this.mUIORText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIORText;
            }
        }
        
        public WpfEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Username";
                    this.mUIUsernameEdit.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public WpfText UIUsernameIndicator
        {
            get
            {
                if ((this.mUIUsernameIndicator == null))
                {
                    this.mUIUsernameIndicator = new WpfText(this);
                    #region Search Criteria
                    this.mUIUsernameIndicator.SearchProperties[WpfText.PropertyNames.AutomationId] = "UsernameWatermark";
                    this.mUIUsernameIndicator.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIUsernameIndicator;
            }
        }
        
        public WpfText UIPasswordIndicator
        {
            get
            {
                if ((this.mUIPasswordIndicator == null))
                {
                    this.mUIPasswordIndicator = new WpfText(this);
                    #region Search Criteria
                    this.mUIPasswordIndicator.SearchProperties[WpfText.PropertyNames.AutomationId] = "PasswordWatermark";
                    this.mUIPasswordIndicator.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPasswordIndicator;
            }
        }
        
        public WpfEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WpfButton UISignInButton
        {
            get
            {
                if ((this.mUISignInButton == null))
                {
                    this.mUISignInButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISignInButton.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    this.mUISignInButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignInButton;
            }
        }
        
        public WpfHyperlink UIForgotPassHyperlink
        {
            get
            {
                if ((this.mUIForgotPassHyperlink == null))
                {
                    this.mUIForgotPassHyperlink = new WpfHyperlink(this);
                    #region Search Criteria
                    this.mUIForgotPassHyperlink.SearchProperties[WpfHyperlink.PropertyNames.Name] = " ";
                    this.mUIForgotPassHyperlink.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIForgotPassHyperlink;
            }
        }
        
        public WpfButton UISignUpButton
        {
            get
            {
                if ((this.mUISignUpButton == null))
                {
                    this.mUISignUpButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISignUpButton.SearchProperties[WpfButton.PropertyNames.Name] = "No account? Sign up, it\'s free!";
                    this.mUISignUpButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignUpButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUISignInText;
        
        private WpfButton mUIGoogleSignInButton;
        
        private WpfText mUIORText;
        
        private WpfEdit mUIUsernameEdit;
        
        private WpfText mUIUsernameIndicator;
        
        private WpfText mUIPasswordIndicator;
        
        private WpfEdit mUIPasswordEdit;
        
        private WpfButton mUISignInButton;
        
        private WpfHyperlink mUIForgotPassHyperlink;
        
        private WpfButton mUISignUpButton;
        #endregion
    }
}
