// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.MainControlPanelClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class MainControlPanel
    {
        
        #region Properties
        public UIPersonifyControlPaneWindow UIPersonifyControlPaneWindow
        {
            get
            {
                if ((this.mUIPersonifyControlPaneWindow == null))
                {
                    this.mUIPersonifyControlPaneWindow = new UIPersonifyControlPaneWindow();
                }
                return this.mUIPersonifyControlPaneWindow;
            }
        }
        
        public UIYouRecordingWindow UIYouRecordingWindow
        {
            get
            {
                if ((this.mUIYouRecordingWindow == null))
                {
                    this.mUIYouRecordingWindow = new UIYouRecordingWindow();
                }
                return this.mUIYouRecordingWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyControlPaneWindow mUIPersonifyControlPaneWindow;
        
        private UIYouRecordingWindow mUIYouRecordingWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyControlPaneWindow : WpfWindow
    {
        
        public UIPersonifyControlPaneWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify Control Panel";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfImage UIPersonifyLogoImage
        {
            get
            {
                if ((this.mUIPersonifyLogoImage == null))
                {
                    this.mUIPersonifyLogoImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIPersonifyLogoImage.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIPersonifyLogoImage;
            }
        }
        
        public WpfButton UISettingsButton
        {
            get
            {
                if ((this.mUISettingsButton == null))
                {
                    this.mUISettingsButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISettingsButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Settings";
                    this.mUISettingsButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUISettingsButton;
            }
        }
        
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public WpfToggleButton UICollaborationToggleButton
        {
            get
            {
                if ((this.mUICollaborationToggleButton == null))
                {
                    this.mUICollaborationToggleButton = new WpfToggleButton(this);
                    #region Search Criteria
                    this.mUICollaborationToggleButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUICollaborationToggleButton;
            }
        }
        
        public WpfToggleButton UIRecordingToggleButton
        {
            get
            {
                if ((this.mUIRecordingToggleButton == null))
                {
                    this.mUIRecordingToggleButton = new WpfToggleButton(this);
                    #region Search Criteria
                    this.mUIRecordingToggleButton.SearchProperties[WpfToggleButton.PropertyNames.Instance] = "2";
                    this.mUIRecordingToggleButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIRecordingToggleButton;
            }
        }
        
        public UIStartCallCustom UIStartCallCustom
        {
            get
            {
                if ((this.mUIStartCallCustom == null))
                {
                    this.mUIStartCallCustom = new UIStartCallCustom(this);
                }
                return this.mUIStartCallCustom;
            }
        }
        
        public UIJoinCallCustom UIJoinCallCustom
        {
            get
            {
                if ((this.mUIJoinCallCustom == null))
                {
                    this.mUIJoinCallCustom = new UIJoinCallCustom(this);
                }
                return this.mUIJoinCallCustom;
            }
        }
        
        public UISettingsCustom UISettingsCustom
        {
            get
            {
                if ((this.mUISettingsCustom == null))
                {
                    this.mUISettingsCustom = new UISettingsCustom(this);
                }
                return this.mUISettingsCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIPersonifyLogoImage;
        
        private WpfButton mUISettingsButton;
        
        private WpfButton mUICloseButton;
        
        private WpfToggleButton mUICollaborationToggleButton;
        
        private WpfToggleButton mUIRecordingToggleButton;
        
        private UIStartCallCustom mUIStartCallCustom;
        
        private UIJoinCallCustom mUIJoinCallCustom;
        
        private UISettingsCustom mUISettingsCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIStartCallCustom : WpfCustom
    {
        
        public UIStartCallCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.SimpleCollaborateUC";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public UIStartCustom UIStartCustom
        {
            get
            {
                if ((this.mUIStartCustom == null))
                {
                    this.mUIStartCustom = new UIStartCustom(this);
                }
                return this.mUIStartCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIStartCustom mUIStartCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIStartCustom : WpfCustom
    {
        
        public UIStartCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.CollabTabUC";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfButton UIStartcallButton
        {
            get
            {
                if ((this.mUIStartcallButton == null))
                {
                    this.mUIStartcallButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartcallButton.SearchProperties[WpfButton.PropertyNames.Name] = "Start call";
                    this.mUIStartcallButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIStartcallButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIStartcallButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIJoinCallCustom : WpfCustom
    {
        
        public UIJoinCallCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.CollabTabUC";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public UIPART_TextEdit UIPART_TextEdit
        {
            get
            {
                if ((this.mUIPART_TextEdit == null))
                {
                    this.mUIPART_TextEdit = new UIPART_TextEdit(this);
                }
                return this.mUIPART_TextEdit;
            }
        }
        #endregion
        
        #region Fields
        private UIPART_TextEdit mUIPART_TextEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPART_TextEdit : WpfEdit
    {
        
        public UIPART_TextEdit(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PART_Text";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfButton UIJoinCallButton
        {
            get
            {
                if ((this.mUIJoinCallButton == null))
                {
                    this.mUIJoinCallButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIJoinCallButton.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIJoinCallButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIJoinCallButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIJoinCallButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISettingsCustom : WpfCustom
    {
        
        public UISettingsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.SettingsUC";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfText UISettingsText
        {
            get
            {
                if ((this.mUISettingsText == null))
                {
                    this.mUISettingsText = new WpfText(this);
                    #region Search Criteria
                    this.mUISettingsText.SearchProperties[WpfText.PropertyNames.Name] = "Settings";
                    this.mUISettingsText.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUISettingsText;
            }
        }
        
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public WpfText UIPthphienText
        {
            get
            {
                if ((this.mUIPthphienText == null))
                {
                    this.mUIPthphienText = new WpfText(this);
                    #region Search Criteria
                    this.mUIPthphienText.SearchProperties[WpfText.PropertyNames.Name] = "pthphien";
                    this.mUIPthphienText.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIPthphienText;
            }
        }
        
        public UIDEVICESGroup UIDEVICESGroup
        {
            get
            {
                if ((this.mUIDEVICESGroup == null))
                {
                    this.mUIDEVICESGroup = new UIDEVICESGroup(this);
                }
                return this.mUIDEVICESGroup;
            }
        }
        
        public UINeedHelpText UINeedHelpText
        {
            get
            {
                if ((this.mUINeedHelpText == null))
                {
                    this.mUINeedHelpText = new UINeedHelpText(this);
                }
                return this.mUINeedHelpText;
            }
        }
        
        public WpfButton UISignOutButton
        {
            get
            {
                if ((this.mUISignOutButton == null))
                {
                    this.mUISignOutButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISignOutButton.SearchProperties[WpfButton.PropertyNames.Name] = "Sign Out";
                    this.mUISignOutButton.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUISignOutButton;
            }
        }
        
        public WpfText UIVersion2350Text
        {
            get
            {
                if ((this.mUIVersion2350Text == null))
                {
                    this.mUIVersion2350Text = new WpfText(this);
                    #region Search Criteria
                    this.mUIVersion2350Text.SearchProperties[WpfText.PropertyNames.Name] = "Version 2.3.5.0";
                    this.mUIVersion2350Text.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIVersion2350Text;
            }
        }
        
        public UIViewLicensesText UIViewLicensesText
        {
            get
            {
                if ((this.mUIViewLicensesText == null))
                {
                    this.mUIViewLicensesText = new UIViewLicensesText(this);
                }
                return this.mUIViewLicensesText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUISettingsText;
        
        private WpfButton mUICloseButton;
        
        private WpfText mUIPthphienText;
        
        private UIDEVICESGroup mUIDEVICESGroup;
        
        private UINeedHelpText mUINeedHelpText;
        
        private WpfButton mUISignOutButton;
        
        private WpfText mUIVersion2350Text;
        
        private UIViewLicensesText mUIViewLicensesText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDEVICESGroup : WpfGroup
    {
        
        public UIDEVICESGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.Name] = "DEVICES";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfText UIDEVICESText
        {
            get
            {
                if ((this.mUIDEVICESText == null))
                {
                    this.mUIDEVICESText = new WpfText(this);
                    #region Search Criteria
                    this.mUIDEVICESText.SearchProperties[WpfText.PropertyNames.Name] = "DEVICES";
                    this.mUIDEVICESText.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIDEVICESText;
            }
        }
        
        public WpfText UIMicrophoneText
        {
            get
            {
                if ((this.mUIMicrophoneText == null))
                {
                    this.mUIMicrophoneText = new WpfText(this);
                    #region Search Criteria
                    this.mUIMicrophoneText.SearchProperties[WpfText.PropertyNames.Name] = "Microphone";
                    this.mUIMicrophoneText.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIMicrophoneText;
            }
        }
        
        public WpfComboBox UIMicrophoneComboBox
        {
            get
            {
                if ((this.mUIMicrophoneComboBox == null))
                {
                    this.mUIMicrophoneComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIMicrophoneComboBox.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIMicrophoneComboBox;
            }
        }
        
        public WpfText UISpeakerText
        {
            get
            {
                if ((this.mUISpeakerText == null))
                {
                    this.mUISpeakerText = new WpfText(this);
                    #region Search Criteria
                    this.mUISpeakerText.SearchProperties[WpfText.PropertyNames.Name] = "Speaker";
                    this.mUISpeakerText.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUISpeakerText;
            }
        }
        
        public WpfComboBox UISpearkersComboBox
        {
            get
            {
                if ((this.mUISpearkersComboBox == null))
                {
                    this.mUISpearkersComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUISpearkersComboBox.SearchProperties[WpfComboBox.PropertyNames.Instance] = "2";
                    this.mUISpearkersComboBox.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUISpearkersComboBox;
            }
        }
        
        public UIWebcamText UIWebcamText
        {
            get
            {
                if ((this.mUIWebcamText == null))
                {
                    this.mUIWebcamText = new UIWebcamText(this);
                }
                return this.mUIWebcamText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIDEVICESText;
        
        private WpfText mUIMicrophoneText;
        
        private WpfComboBox mUIMicrophoneComboBox;
        
        private WpfText mUISpeakerText;
        
        private WpfComboBox mUISpearkersComboBox;
        
        private UIWebcamText mUIWebcamText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIWebcamText : WpfText
    {
        
        public UIWebcamText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Webcam";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfComboBox UIWebcamComboBox
        {
            get
            {
                if ((this.mUIWebcamComboBox == null))
                {
                    this.mUIWebcamComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIWebcamComboBox.SearchProperties[WpfComboBox.PropertyNames.Instance] = "3";
                    this.mUIWebcamComboBox.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIWebcamComboBox.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIWebcamComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfComboBox mUIWebcamComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UINeedHelpText : WpfText
    {
        
        public UINeedHelpText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Need Help?";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfHyperlink UINeedHelpHyperlink
        {
            get
            {
                if ((this.mUINeedHelpHyperlink == null))
                {
                    this.mUINeedHelpHyperlink = new WpfHyperlink(this);
                    #region Search Criteria
                    this.mUINeedHelpHyperlink.SearchProperties[WpfHyperlink.PropertyNames.Name] = "Need Help?";
                    this.mUINeedHelpHyperlink.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUINeedHelpHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WpfHyperlink mUINeedHelpHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIViewLicensesText : WpfText
    {
        
        public UIViewLicensesText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "View Licenses";
            this.WindowTitles.Add("Personify Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfHyperlink UIViewLicensesHyperlink
        {
            get
            {
                if ((this.mUIViewLicensesHyperlink == null))
                {
                    this.mUIViewLicensesHyperlink = new WpfHyperlink(this);
                    #region Search Criteria
                    this.mUIViewLicensesHyperlink.SearchProperties[WpfHyperlink.PropertyNames.Name] = "View Licenses";
                    this.mUIViewLicensesHyperlink.WindowTitles.Add("Personify Control Panel");
                    #endregion
                }
                return this.mUIViewLicensesHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WpfHyperlink mUIViewLicensesHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIYouRecordingWindow : WpfWindow
    {
        
        public UIYouRecordingWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "You";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("You");
            #endregion
        }
        
        #region Properties
        public WpfImage UILocalUserImageImage
        {
            get
            {
                if ((this.mUILocalUserImageImage == null))
                {
                    this.mUILocalUserImageImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUILocalUserImageImage.SearchProperties[WpfImage.PropertyNames.AutomationId] = "LocalUserImage";
                    this.mUILocalUserImageImage.WindowTitles.Add("You");
                    #endregion
                }
                return this.mUILocalUserImageImage;
            }
        }
        
        public WpfImage UILocalUserWatermarkImage
        {
            get
            {
                if ((this.mUILocalUserWatermarkImage == null))
                {
                    this.mUILocalUserWatermarkImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUILocalUserWatermarkImage.SearchProperties[WpfImage.PropertyNames.AutomationId] = "LocalUserWatermark";
                    this.mUILocalUserWatermarkImage.WindowTitles.Add("You");
                    #endregion
                }
                return this.mUILocalUserWatermarkImage;
            }
        }
        
        public UIMPersonaResizerSlider UIMPersonaResizerSlider
        {
            get
            {
                if ((this.mUIMPersonaResizerSlider == null))
                {
                    this.mUIMPersonaResizerSlider = new UIMPersonaResizerSlider(this);
                }
                return this.mUIMPersonaResizerSlider;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUILocalUserImageImage;
        
        private WpfImage mUILocalUserWatermarkImage;
        
        private UIMPersonaResizerSlider mUIMPersonaResizerSlider;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMPersonaResizerSlider : WpfSlider
    {
        
        public UIMPersonaResizerSlider(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfSlider.PropertyNames.AutomationId] = "mPersonaResizer";
            this.WindowTitles.Add("You");
            #endregion
        }
        
        #region Properties
        public WpfControl UIThumbIndicator
        {
            get
            {
                if ((this.mUIThumbIndicator == null))
                {
                    this.mUIThumbIndicator = new WpfControl(this);
                    #region Search Criteria
                    this.mUIThumbIndicator.SearchProperties[UITestControl.PropertyNames.ControlType] = "Indicator";
                    this.mUIThumbIndicator.SearchProperties["AutomationId"] = "Thumb";
                    this.mUIThumbIndicator.WindowTitles.Add("You");
                    #endregion
                }
                return this.mUIThumbIndicator;
            }
        }
        #endregion
        
        #region Fields
        private WpfControl mUIThumbIndicator;
        #endregion
    }
}
