// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.SignUpUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class SignUpUIMap
    {
        
        #region Properties
        public UIPersonifyWindow UIPersonifyWindow
        {
            get
            {
                if ((this.mUIPersonifyWindow == null))
                {
                    this.mUIPersonifyWindow = new UIPersonifyWindow();
                }
                return this.mUIPersonifyWindow;
            }
        }
        
        public UIPersonifySignUpSubForm UIPersonifySignUpSubForm
        {
            get
            {
                if ((this.mUIPersonifySignUpSubForm == null))
                {
                    this.mUIPersonifySignUpSubForm = new UIPersonifySignUpSubForm();
                }
                return this.mUIPersonifySignUpSubForm;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyWindow mUIPersonifyWindow;
        
        private UIPersonifySignUpSubForm mUIPersonifySignUpSubForm;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyWindow : WpfWindow
    {
        
        public UIPersonifyWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public WpfButton UISignUpMainMenu
        {
            get
            {
                if ((this.mUISignUpMainMenu == null))
                {
                    this.mUISignUpMainMenu = new WpfButton(this);
                    #region Search Criteria
                    this.mUISignUpMainMenu.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignUpMainMenu;
            }
        }
        
        public UIPersonifySignUpForm UIPersonifySignUpForm
        {
            get
            {
                if ((this.mUIPersonifySignUpForm == null))
                {
                    this.mUIPersonifySignUpForm = new UIPersonifySignUpForm(this);
                }
                return this.mUIPersonifySignUpForm;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICloseButton;
        
        private WpfButton mUISignUpMainMenu;
        
        private UIPersonifySignUpForm mUIPersonifySignUpForm;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifySignUpForm : WpfCustom
    {
        
        public UIPersonifySignUpForm(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.RegisterWebUC";
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfButton UIGoogleSignUpButton
        {
            get
            {
                if ((this.mUIGoogleSignUpButton == null))
                {
                    this.mUIGoogleSignUpButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIGoogleSignUpButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIGoogleSignUpButton;
            }
        }
        
        public WpfText UIORText
        {
            get
            {
                if ((this.mUIORText == null))
                {
                    this.mUIORText = new WpfText(this);
                    #region Search Criteria
                    this.mUIORText.SearchProperties[WpfText.PropertyNames.Name] = "or";
                    this.mUIORText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIORText;
            }
        }
        
        public WpfText UISignUpText
        {
            get
            {
                if ((this.mUISignUpText == null))
                {
                    this.mUISignUpText = new WpfText(this);
                    #region Search Criteria
                    this.mUISignUpText.SearchProperties[WpfText.PropertyNames.Name] = "Sign Up";
                    this.mUISignUpText.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUISignUpText;
            }
        }
        
        public WpfButton UIAlreadyhaveanaccountButton
        {
            get
            {
                if ((this.mUIAlreadyhaveanaccountButton == null))
                {
                    this.mUIAlreadyhaveanaccountButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAlreadyhaveanaccountButton.SearchProperties[WpfButton.PropertyNames.Name] = "Already have an account? Sign In";
                    this.mUIAlreadyhaveanaccountButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIAlreadyhaveanaccountButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIGoogleSignUpButton;
        
        private WpfText mUIORText;
        
        private WpfText mUISignUpText;
        
        private WpfButton mUIAlreadyhaveanaccountButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifySignUpSubForm : WinClient
    {
        
        public UIPersonifySignUpSubForm()
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            #endregion
        }
        
        #region Properties
        public UIPersonifyOmniCreateDocument UIPersonifyOmniCreateDocument
        {
            get
            {
                if ((this.mUIPersonifyOmniCreateDocument == null))
                {
                    this.mUIPersonifyOmniCreateDocument = new UIPersonifyOmniCreateDocument(this);
                }
                return this.mUIPersonifyOmniCreateDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyOmniCreateDocument mUIPersonifyOmniCreateDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyOmniCreateDocument : HtmlDocument
    {
        
        public UIPersonifyOmniCreateDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Personify Omni - Create account";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/api/register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://dev.personifyinc.com/api/register?lang=en-US";
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIPersonifySignUpSubPanel
        {
            get
            {
                if ((this.mUIPersonifySignUpSubPanel == null))
                {
                    this.mUIPersonifySignUpSubPanel = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIPersonifySignUpSubPanel.SearchProperties[HtmlDiv.PropertyNames.Id] = "omni-users-form-container";
                    this.mUIPersonifySignUpSubPanel.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIPersonifySignUpSubPanel.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign Up for Personify!\r\n \r\n   \r\n  I agre";
                    this.mUIPersonifySignUpSubPanel.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIPersonifySignUpSubPanel.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIPersonifySignUpSubPanel.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=omni-users-form-container";
                    this.mUIPersonifySignUpSubPanel.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIPersonifySignUpSubPanel;
            }
        }
        
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_first_name";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[first_name]";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[first_name] tabIndex=1 class=p";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_last_name";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[last_name]";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[last_name] tabIndex=2 class=pl";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }
        
        public HtmlEdit UIUseremailEdit
        {
            get
            {
                if ((this.mUIUseremailEdit == null))
                {
                    this.mUIUseremailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUseremailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_email";
                    this.mUIUseremailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[email]";
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[email] tabIndex=3 class=placeh";
                    this.mUIUseremailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    #endregion
                }
                return this.mUIUseremailEdit;
            }
        }
        
        public HtmlEdit UIUser_passwordEdit
        {
            get
            {
                if ((this.mUIUser_passwordEdit == null))
                {
                    this.mUIUser_passwordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUser_passwordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_password";
                    this.mUIUser_passwordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIUser_passwordEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUser_passwordEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUser_passwordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUser_passwordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIUser_passwordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=4 class=placeholder id=User_pas";
                    this.mUIUser_passwordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    #endregion
                }
                return this.mUIUser_passwordEdit;
            }
        }
        
        public HtmlEdit UIRepeatEdit
        {
            get
            {
                if ((this.mUIRepeatEdit == null))
                {
                    this.mUIRepeatEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIRepeatEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_password_repeat";
                    this.mUIRepeatEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIRepeatEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIRepeatEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIRepeatEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIRepeatEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIRepeatEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=5 class=placeholder id=User_pas";
                    this.mUIRepeatEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    #endregion
                }
                return this.mUIRepeatEdit;
            }
        }
        
        public HtmlCheckBox UIAgreeTermsCheckBox
        {
            get
            {
                if ((this.mUIAgreeTermsCheckBox == null))
                {
                    this.mUIAgreeTermsCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIAgreeTermsCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "terms_service_cb";
                    this.mUIAgreeTermsCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "User[terms_service]";
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "1";
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "I agree to the Terms of Service  ";
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = "ez-hide";
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=User[terms_service] tabIndex=6 clas";
                    this.mUIAgreeTermsCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "10";
                    #endregion
                }
                return this.mUIAgreeTermsCheckBox;
            }
        }
        
        public UIIagreetotheTermsofSeLabel UIIagreetotheTermsofSeLabel
        {
            get
            {
                if ((this.mUIIagreetotheTermsofSeLabel == null))
                {
                    this.mUIIagreetotheTermsofSeLabel = new UIIagreetotheTermsofSeLabel(this);
                }
                return this.mUIIagreetotheTermsofSeLabel;
            }
        }
        
        public HtmlInputButton UICreateAccountButton
        {
            get
            {
                if ((this.mUICreateAccountButton == null))
                {
                    this.mUICreateAccountButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateAccountButton.SearchProperties[HtmlButton.PropertyNames.Id] = "register-btn";
                    this.mUICreateAccountButton.SearchProperties[HtmlButton.PropertyNames.Name] = "create";
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Create your account";
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary inactive is-small-separator disabled";
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=create disabled class=\"btn btn-prim";
                    this.mUICreateAccountButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "11";
                    #endregion
                }
                return this.mUICreateAccountButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIPersonifySignUpSubPanel;
        
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlEdit mUILastNameEdit;
        
        private HtmlEdit mUIUseremailEdit;
        
        private HtmlEdit mUIUser_passwordEdit;
        
        private HtmlEdit mUIRepeatEdit;
        
        private HtmlCheckBox mUIAgreeTermsCheckBox;
        
        private UIIagreetotheTermsofSeLabel mUIIagreetotheTermsofSeLabel;
        
        private HtmlInputButton mUICreateAccountButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIIagreetotheTermsofSeLabel : HtmlLabel
    {
        
        public UIIagreetotheTermsofSeLabel(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlLabel.PropertyNames.Id] = "terms_service";
            this.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
            this.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "terms_service_cb";
            this.FilterProperties[HtmlLabel.PropertyNames.InnerText] = "I agree to the Terms of Service  ";
            this.FilterProperties[HtmlLabel.PropertyNames.Class] = "checkbox";
            this.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "class=checkbox id=terms_service for=term";
            this.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "1";
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITermsofServiceHyperlink
        {
            get
            {
                if ((this.mUITermsofServiceHyperlink == null))
                {
                    this.mUITermsofServiceHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Terms of Service";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/corporate/terms";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://dev.personifyinc.com/corporate/terms";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "u";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=u href=\"/corporate/terms\" target=_";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUITermsofServiceHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITermsofServiceHyperlink;
        #endregion
    }
}
