// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.SignUpUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class SignUpUIMap
    {
        
        #region Properties
        public UIPersonifyWindow UIPersonifyWindow
        {
            get
            {
                if ((this.mUIPersonifyWindow == null))
                {
                    this.mUIPersonifyWindow = new UIPersonifyWindow();
                }
                return this.mUIPersonifyWindow;
            }
        }
        
        public UISignUpFormClient UISignUpFormClient
        {
            get
            {
                if ((this.mUISignUpFormClient == null))
                {
                    this.mUISignUpFormClient = new UISignUpFormClient();
                }
                return this.mUISignUpFormClient;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyWindow mUIPersonifyWindow;
        
        private UISignUpFormClient mUISignUpFormClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyWindow : WpfWindow
    {
        
        public UIPersonifyWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Personify";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfImage UIPersonifyLogoImage
        {
            get
            {
                if ((this.mUIPersonifyLogoImage == null))
                {
                    this.mUIPersonifyLogoImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIPersonifyLogoImage.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIPersonifyLogoImage;
            }
        }
        
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        
        public UIGobackText UIGobackText
        {
            get
            {
                if ((this.mUIGobackText == null))
                {
                    this.mUIGobackText = new UIGobackText(this);
                }
                return this.mUIGobackText;
            }
        }
        #endregion
        
        #region Fields
        private WpfImage mUIPersonifyLogoImage;
        
        private WpfButton mUICloseButton;
        
        private UIGobackText mUIGobackText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIGobackText : WpfText
    {
        
        public UIGobackText(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Go back";
            this.WindowTitles.Add("Personify");
            #endregion
        }
        
        #region Properties
        public WpfHyperlink UIGobackHyperlink
        {
            get
            {
                if ((this.mUIGobackHyperlink == null))
                {
                    this.mUIGobackHyperlink = new WpfHyperlink(this);
                    #region Search Criteria
                    this.mUIGobackHyperlink.SearchProperties[WpfHyperlink.PropertyNames.Name] = "Go back";
                    this.mUIGobackHyperlink.WindowTitles.Add("Personify");
                    #endregion
                }
                return this.mUIGobackHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private WpfHyperlink mUIGobackHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISignUpFormClient : WinClient
    {
        
        public UISignUpFormClient()
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            #endregion
        }
        
        #region Properties
        public UIPersonifyOmniCreateaDocument UIPersonifyOmniCreateaDocument
        {
            get
            {
                if ((this.mUIPersonifyOmniCreateaDocument == null))
                {
                    this.mUIPersonifyOmniCreateaDocument = new UIPersonifyOmniCreateaDocument(this);
                }
                return this.mUIPersonifyOmniCreateaDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIPersonifyOmniCreateaDocument mUIPersonifyOmniCreateaDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPersonifyOmniCreateaDocument : HtmlDocument
    {
        
        public UIPersonifyOmniCreateaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Personify Omni - Create account";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/api/register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://omni.personifyinc.com/api/register";
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIOmniusersformcontainPane
        {
            get
            {
                if ((this.mUIOmniusersformcontainPane == null))
                {
                    this.mUIOmniusersformcontainPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIOmniusersformcontainPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "omni-users-form-container";
                    this.mUIOmniusersformcontainPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIOmniusersformcontainPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign Up for Personify!\r\n \r\n   \r\n First N";
                    this.mUIOmniusersformcontainPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIOmniusersformcontainPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIOmniusersformcontainPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=omni-users-form-container";
                    this.mUIOmniusersformcontainPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIOmniusersformcontainPane;
            }
        }
        
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_first_name";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[first_name]";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[first_name] tabIndex=1 class=p";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_last_name";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[last_name]";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[last_name] tabIndex=2 class=pl";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }
        
        public HtmlEdit UIUserEmailEdit
        {
            get
            {
                if ((this.mUIUserEmailEdit == null))
                {
                    this.mUIUserEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUserEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_email";
                    this.mUIUserEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "User[email]";
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=User[email] tabIndex=3 class=placeh";
                    this.mUIUserEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    #endregion
                }
                return this.mUIUserEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordplaceholderEdit
        {
            get
            {
                if ((this.mUIPasswordplaceholderEdit == null))
                {
                    this.mUIPasswordplaceholderEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_password-placeholder";
                    this.mUIPasswordplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIPasswordplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPasswordplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIPasswordplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=4 class=placeholder id=User_pas";
                    this.mUIPasswordplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    #endregion
                }
                return this.mUIPasswordplaceholderEdit;
            }
        }
        
        public HtmlEdit UIRepeatplaceholderEdit
        {
            get
            {
                if ((this.mUIRepeatplaceholderEdit == null))
                {
                    this.mUIRepeatplaceholderEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIRepeatplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "User_password_repeat-placeholder";
                    this.mUIRepeatplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIRepeatplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIRepeatplaceholderEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIRepeatplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIRepeatplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "placeholder";
                    this.mUIRepeatplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabIndex=5 class=placeholder id=User_pas";
                    this.mUIRepeatplaceholderEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    #endregion
                }
                return this.mUIRepeatplaceholderEdit;
            }
        }
        
        public HtmlDiv UIFirstNameBlankWarning
        {
            get
            {
                if ((this.mUIFirstNameBlankWarning == null))
                {
                    this.mUIFirstNameBlankWarning = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIFirstNameBlankWarning.SearchProperties[HtmlDiv.PropertyNames.Id] = "User_first_name_em_";
                    this.mUIFirstNameBlankWarning.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIFirstNameBlankWarning.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "First Name cannot be blank.";
                    this.mUIFirstNameBlankWarning.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIFirstNameBlankWarning.FilterProperties[HtmlDiv.PropertyNames.Class] = "errorMessage errorMessaged";
                    this.mUIFirstNameBlankWarning.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"errorMessage errorMessaged\" id=Us";
                    this.mUIFirstNameBlankWarning.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "21";
                    #endregion
                }
                return this.mUIFirstNameBlankWarning;
            }
        }
        
        public HtmlCheckBox UIIagreetotheTermsofSeCheckBox
        {
            get
            {
                if ((this.mUIIagreetotheTermsofSeCheckBox == null))
                {
                    this.mUIIagreetotheTermsofSeCheckBox = new HtmlCheckBox(this);
                    #region Search Criteria
                    this.mUIIagreetotheTermsofSeCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = "terms_service_cb";
                    this.mUIIagreetotheTermsofSeCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "User[terms_service]";
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Value] = "1";
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.LabeledBy] = "I agree to the Terms of Service  ";
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = "ez-hide";
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=User[terms_service] tabIndex=6 clas";
                    this.mUIIagreetotheTermsofSeCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "10";
                    #endregion
                }
                return this.mUIIagreetotheTermsofSeCheckBox;
            }
        }
        
        public UIIagreetotheTermsofSeLabel UIIagreetotheTermsofSeLabel
        {
            get
            {
                if ((this.mUIIagreetotheTermsofSeLabel == null))
                {
                    this.mUIIagreetotheTermsofSeLabel = new UIIagreetotheTermsofSeLabel(this);
                }
                return this.mUIIagreetotheTermsofSeLabel;
            }
        }
        
        public HtmlInputButton UICreateyouraccountButton
        {
            get
            {
                if ((this.mUICreateyouraccountButton == null))
                {
                    this.mUICreateyouraccountButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateyouraccountButton.SearchProperties[HtmlButton.PropertyNames.Id] = "register-btn";
                    this.mUICreateyouraccountButton.SearchProperties[HtmlButton.PropertyNames.Name] = "yt0";
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Create your account";
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary inactive is-small-separator disabled";
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=yt0 disabled class=\"btn btn-primary";
                    this.mUICreateyouraccountButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "11";
                    #endregion
                }
                return this.mUICreateyouraccountButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIOmniusersformcontainPane;
        
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlEdit mUILastNameEdit;
        
        private HtmlEdit mUIUserEmailEdit;
        
        private HtmlEdit mUIPasswordplaceholderEdit;
        
        private HtmlEdit mUIRepeatplaceholderEdit;
        
        private HtmlDiv mUIFirstNameBlankWarning;
        
        private HtmlCheckBox mUIIagreetotheTermsofSeCheckBox;
        
        private UIIagreetotheTermsofSeLabel mUIIagreetotheTermsofSeLabel;
        
        private HtmlInputButton mUICreateyouraccountButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIIagreetotheTermsofSeLabel : HtmlLabel
    {
        
        public UIIagreetotheTermsofSeLabel(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlLabel.PropertyNames.Id] = "terms_service";
            this.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
            this.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "terms_service_cb";
            this.FilterProperties[HtmlLabel.PropertyNames.InnerText] = "I agree to the Terms of Service  ";
            this.FilterProperties[HtmlLabel.PropertyNames.Class] = "checkbox";
            this.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "class=checkbox id=terms_service for=term";
            this.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "1";
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITermsofServiceHyperlink
        {
            get
            {
                if ((this.mUITermsofServiceHyperlink == null))
                {
                    this.mUITermsofServiceHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = "_blank";
                    this.mUITermsofServiceHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Terms of Service";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/corporate/terms";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://omni.personifyinc.com/corporate/terms";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "u";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabIndex=7 class=u href=\"/corporate/term";
                    this.mUITermsofServiceHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    #endregion
                }
                return this.mUITermsofServiceHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITermsofServiceHyperlink;
        #endregion
    }
}
