// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.VideoCallTextChatUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class VideoCallTextChatUIMap
    {
        
        #region Properties
        public UITextChatDialog UITextChatDialog
        {
            get
            {
                if ((this.mUITextChatDialog == null))
                {
                    this.mUITextChatDialog = new UITextChatDialog();
                }
                return this.mUITextChatDialog;
            }
        }
        #endregion
        
        #region Fields
        private UITextChatDialog mUITextChatDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITextChatDialog : WpfWindow
    {
        
        public UITextChatDialog()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Control Panel";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Control Panel");
            #endregion
        }
        
        #region Properties
        public UITextChatForm UITextChatForm
        {
            get
            {
                if ((this.mUITextChatForm == null))
                {
                    this.mUITextChatForm = new UITextChatForm(this);
                }
                return this.mUITextChatForm;
            }
        }
        #endregion
        
        #region Fields
        private UITextChatForm mUITextChatForm;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITextChatForm : WpfCustom
    {
        
        public UITextChatForm(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "Uia.ChatTabViewUC";
            this.WindowTitles.Add("Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITextChatEdit
        {
            get
            {
                if ((this.mUITextChatEdit == null))
                {
                    this.mUITextChatEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextChatEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "mTypeTexBox";
                    this.mUITextChatEdit.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUITextChatEdit;
            }
        }
        
        public WpfText UITextChatIndicator
        {
            get
            {
                if ((this.mUITextChatIndicator == null))
                {
                    this.mUITextChatIndicator = new WpfText(this);
                    #region Search Criteria
                    this.mUITextChatIndicator.SearchProperties[WpfText.PropertyNames.Name] = "Say something to everyone...";
                    this.mUITextChatIndicator.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUITextChatIndicator;
            }
        }
        
        public WpfButton UIUploadfileButton
        {
            get
            {
                if ((this.mUIUploadfileButton == null))
                {
                    this.mUIUploadfileButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIUploadfileButton.SearchProperties[WpfButton.PropertyNames.Name] = "Upload file...";
                    this.mUIUploadfileButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIUploadfileButton;
            }
        }
        
        public WpfButton UIConversationButton
        {
            get
            {
                if ((this.mUIConversationButton == null))
                {
                    this.mUIConversationButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIConversationButton.SearchProperties[WpfButton.PropertyNames.Name] = "Conversation";
                    this.mUIConversationButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIConversationButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITextChatEdit;
        
        private WpfText mUITextChatIndicator;
        
        private WpfButton mUIUploadfileButton;
        
        private WpfButton mUIConversationButton;
        #endregion
    }
}
