// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace OmniCodedUITest.UIMaps.VideoCallUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class VideoCallUIMap
    {
        
        #region Properties
        public UIVideoCallControlPanelWindow UIVideoCallControlPanelWindow
        {
            get
            {
                if ((this.mUIVideoCallControlPanelWindow == null))
                {
                    this.mUIVideoCallControlPanelWindow = new UIVideoCallControlPanelWindow();
                }
                return this.mUIVideoCallControlPanelWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIVideoCallControlPanelWindow mUIVideoCallControlPanelWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIVideoCallControlPanelWindow : WpfWindow
    {
        
        public UIVideoCallControlPanelWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Control Panel";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Control Panel");
            #endregion
        }
        
        #region Properties
        public WpfToggleButton UIVideoCallControlPanelMenu
        {
            get
            {
                if ((this.mUIVideoCallControlPanelMenu == null))
                {
                    this.mUIVideoCallControlPanelMenu = new WpfToggleButton(this);
                    #region Search Criteria
                    this.mUIVideoCallControlPanelMenu.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIVideoCallControlPanelMenu;
            }
        }
        
        public WpfToggleButton UITextChatButton
        {
            get
            {
                if ((this.mUITextChatButton == null))
                {
                    this.mUITextChatButton = new WpfToggleButton(this);
                    #region Search Criteria
                    this.mUITextChatButton.SearchProperties[WpfToggleButton.PropertyNames.Instance] = "2";
                    this.mUITextChatButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUITextChatButton;
            }
        }
        
        public WpfButton UIShareWindowButton
        {
            get
            {
                if ((this.mUIShareWindowButton == null))
                {
                    this.mUIShareWindowButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIShareWindowButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIShareWindowButton;
            }
        }
        
        public WpfButton UIMuteVideoButton
        {
            get
            {
                if ((this.mUIMuteVideoButton == null))
                {
                    this.mUIMuteVideoButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIMuteVideoButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Btn";
                    this.mUIMuteVideoButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIMuteVideoButton;
            }
        }
        
        public WpfToggleButton UIAddMemberButton
        {
            get
            {
                if ((this.mUIAddMemberButton == null))
                {
                    this.mUIAddMemberButton = new WpfToggleButton(this);
                    #region Search Criteria
                    this.mUIAddMemberButton.SearchProperties[WpfToggleButton.PropertyNames.Instance] = "5";
                    this.mUIAddMemberButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIAddMemberButton;
            }
        }
        
        public WpfButton UIStopVideoCallButton
        {
            get
            {
                if ((this.mUIStopVideoCallButton == null))
                {
                    this.mUIStopVideoCallButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStopVideoCallButton.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    this.mUIStopVideoCallButton.WindowTitles.Add("Control Panel");
                    #endregion
                }
                return this.mUIStopVideoCallButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfToggleButton mUIVideoCallControlPanelMenu;
        
        private WpfToggleButton mUITextChatButton;
        
        private WpfButton mUIShareWindowButton;
        
        private WpfButton mUIMuteVideoButton;
        
        private WpfToggleButton mUIAddMemberButton;
        
        private WpfButton mUIStopVideoCallButton;
        #endregion
    }
}
